# Generated by Django 3.2 on 2023-07-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_shopcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcategory',
            options={'verbose_name': 'Pharmacy Category', 'verbose_name_plural': 'Pharmacy Categories'},
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Pharmacy catagories'),
        ),
    ]
