# Generated by Django 3.2 on 2023-07-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20230725_1937'),
        ('shops', '0002_shopprofile_shop_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopprofile',
            options={'verbose_name': 'Pharmacy Profile', 'verbose_name_plural': 'Pharmacy Profiles'},
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_bg',
            field=models.ImageField(default='shop_default.jpeg', upload_to='shop_back_grounds', verbose_name='pharmacy background image'),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.shopcategory', verbose_name='pharmacy category'),
        ),
    ]
