# Generated by Django 3.2 on 2023-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20230725_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_address',
            field=models.CharField(max_length=255, verbose_name='Pharmacy address'),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Pharmacy'),
        ),
    ]
