# Generated by Django 3.2 on 2023-07-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20230725_1937'),
        ('shoprequests', '0003_auto_20210209_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoprequest',
            options={'verbose_name': 'Pharmacy Request', 'verbose_name_plural': 'Pharmacy Requests'},
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='shop_address',
            field=models.CharField(max_length=50, null=True, verbose_name='Pharmacy address'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='shop_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.shopcategory', verbose_name='Pharmacy category'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='shop_title',
            field=models.CharField(max_length=50, verbose_name='Pharmacy title'),
        ),
    ]
